---
identify_niche_emerging_markets:
  description: |
    Identify niche and emerging markets (potential whitespaces).
    Create a table to analyzes demand side opportunities (rows) vs. offer side opportunities (columns).
    
    Whitespaces will be the niche or emerging markets where there are opportunities to fill demand side opportunities and challenges with new offer opportunities: 
    they can be either emerging, already existing but fragmented, or still incipient offers.
    
    Relevant information for the analysis and conclusion of the analysis:
     - Demand side opportunities       
     - Offer side opportunities
     - Challenges and barriers
     - Potential solutions and innovations

     Rules:
      - Use only trustworthy sources and provide proper citations.
      - Use the most up-to-date information from 2024 and 2025.
      - Prioritize brazilian sources written in portuguese.
    
    <Knowledge Required>
    
    <Value Chain Analysis>
    {value_chain_analysis}
    </Value Chain Analysis>
    
    <Current and Future Opportunities>
    {current_future_opportunities}
    </Current and Future Opportunities>
    
    <Ongoing Changes Signals>
    {ongoing_changes_signals}
    </Ongoing Changes Signals>
    
    <Current Pains>
    {current_pains}
    </Current Pains>
    
    <Consumption Trends>
    {consumption_trends}
    </Consumption Trends>
    
    </Knowledge Required>
  expected_output: |
    - Table with analysis of demand side opportunities vs. offer side opportunities.
    - List of identified whitespaces (niche and emerging potential markets).
  agent: industry_expert_consultant

qualify_potential_whitespaces:
  description: |
    For each identified whitespace, qualify them with:
      - List of signals related to the demand side;
      - List of signals related to the offer side;
      - Identify which step or steps of the value chain are being affected and how disruptive it might be;
      - Rank the whitespaces according to the strength of market signals;
      - Define the key assumptions and risks associated with that potential market;

    Rules:
      - Use only trustworthy sources and provide proper citations.
      - Use the most up-to-date information from 2024 and 2025.
      - Prioritize brazilian sources written in portuguese.
    
    <Knowledge Required>
    
    <Value Chain Analysis>
    {value_chain_analysis}
    </Value Chain Analysis>
    
    <Current and Future Opportunities>
    {current_future_opportunities}
    </Current and Future Opportunities>
    
    <Ongoing Changes Signals>
    {ongoing_changes_signals}
    </Ongoing Changes Signals>
    
    <Current Pains>
    {current_pains}
    </Current Pains>
    
    <Consumption Trends>
    {consumption_trends}
    </Consumption Trends>
    
    </Knowledge Required>
  expected_output: |
    Qualified list of whitespaces with:
    - Demand side signals related
    - Offer side signals related
    - Affected steps of the value chain
    - Ranking of whitespaces based on market signals
    - Key assumptions and risks for each potential market
    - Challenges and barriers
    - Potential solutions and innovations
  agent: industry_expert_consultant
  context:
    - identify_niche_emerging_markets

calculate_potential_addressable_market:
  description: |
    For each identified whitespace, quantify their potential addressable market by taking the following steps:
    1. Define and list all the key assumptions to determine a formula for calculating the potential addressable market for that specific whitespace. 
       Explain the rationale in detail. We do not need a precise number, ranges and a fair
    2. Research all the numbers necessary for the key assumptions, one by one, listing the rationale and source used to define each number.
    3. Calculate the potential addressable market using the formula defined in step 1 and the numbers researched in step 2. 
       If data is not available for a calculation, simplify assumption and addressable market formula and reiterate.

    Rules:
      - Use only trustworthy sources and provide proper citations.
      - Use the most up-to-date information from 2024 and 2025.
      - Prioritize brazilian sources written in portuguese.
    
    <Knowledge Required>
    
    <Value Chain Analysis>
    {value_chain_analysis}
    </Value Chain Analysis>
    
    <Current and Future Opportunities>
    {current_future_opportunities}
    </Current and Future Opportunities>
    
    <Ongoing Changes Signals>
    {ongoing_changes_signals}
    </Ongoing Changes Signals>
    
    <Current Pains>
    {current_pains}
    </Current Pains>
    
    <Consumption Trends>
    {consumption_trends}
    </Consumption Trends>
    
    </Knowledge Required>
  expected_output: |
    Quantified potential addressable market for each whitespace, including:
    - Key assumptions and detailed rationale
    - Researched numbers with rationale and sources
    - Calculated potential addressable market with defined ranges
  agent: financial_modeling_specialist
  context:
    - qualify_potential_whitespaces

complete_report_mapped_whitespaces:
  description: | 
    Compile the list of potential whitespaces qualified with its respective addressable market calculated

  expected_output: |
    List of potential whitespaces, including:
    - market signals identified
    - potential addressable market

  agent: editorial_agent
  context:
    - qualify_potential_whitespaces
    - calculate_potential_addressable_market
